import Head from "next/head";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import next18nextConfig from "next-18next.config";

import type { GetServerSidePropsContext, NextPage } from "next";

import { Home as Styles } from "@stylesPages";

import { Language, Layout } from "@components";

export const getServerSideProps = async ({ locale }: GetServerSidePropsContext) => ({
  props: {
    ...await serverSideTranslations(
      locale ?? "en-US",
      next18nextConfig.ns,
      next18nextConfig
    )
  }
});

const Home: NextPage = () => {
  const { t } = useTranslation("common");

  return (
    <Layout>
      <Styles.Container>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Language />
        <Styles.Grid>
          <Styles.Card href="https://nextjs.org/docs">
            <Styles.CardTitle>{t("home-title-one")}</Styles.CardTitle>
            <Styles.CardText>{t("home-text-one")}</Styles.CardText>
          </Styles.Card>
          <Styles.Card href="https://nextjs.org/learn">
            <Styles.CardTitle>{t("home-title-two")}</Styles.CardTitle>
            <Styles.CardText>{t("home-text-two")}</Styles.CardText>
          </Styles.Card>
          <Styles.Card
            href="https://github.com/vercel/next.js/tree/master/examples"
          >
            <Styles.CardTitle>{t("home-title-three")}</Styles.CardTitle>
            <Styles.CardText>{t("home-text-three")}</Styles.CardText>
          </Styles.Card>
          <Styles.Card
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          >
            <Styles.CardTitle>{t("home-title-four")}</Styles.CardTitle>
            <Styles.CardText>{t("home-text-four")}</Styles.CardText>
          </Styles.Card>
        </Styles.Grid>
      </Styles.Container>
    </Layout>
  );
};

export default Home;
