import Head from "next/head";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import next18nextConfig from "next-18next.config";

import type { GetServerSidePropsContext, NextPage } from "next";

import styles from "@stylesPages/Home.module.scss";

import { Language, Layout } from "@components";

export const getServerSideProps = async ({ locale }: GetServerSidePropsContext) => ({
  props: {
    ...await serverSideTranslations(
      locale ?? "en-US",
      next18nextConfig.ns,
      next18nextConfig
    )
  }
});

const Home: NextPage = () => {
  const { t } = useTranslation("common");

  return (
    <Layout>
      <div className={styles.home__container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Language />
        <div className={styles.home__grid}>
          <a className={styles.home__card} href="https://nextjs.org/docs">
            <h1 className={styles.home__cardtitle}>{t("home-title-one")}</h1>
            <p className={styles.home__cardtext}>{t("home-text-one")}</p>
          </a>
          <a className={styles.home__card} href="https://nextjs.org/learn">
            <h1 className={styles.home__cardtitle}>{t("home-title-two")}</h1>
            <p className={styles.home__cardtext}>{t("home-text-two")}</p>
          </a>
          <a
            className={styles.home__card}
            href="https://github.com/vercel/next.js/tree/master/examples"
          >
            <h1 className={styles.home__cardtitle}>{t("home-title-three")}</h1>
            <p className={styles.home__cardtext}>{t("home-text-three")}</p>
          </a>
          <a
            className={styles.home__card}
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          >
            <h1 className={styles.home__cardtitle}>{t("home-title-four")}</h1>
            <p className={styles.home__cardtext}>{t("home-text-four")}</p>
          </a>
        </div>
      </div>
    </Layout>
  );
};

export default Home;
